# Generated by Django 5.2.17 on 2026-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='Категория')),
                ('ordering', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('aries', 'Овен'), ('taurus', 'Телец'), ('gemini', 'Близнецы'), ('cancer', 'Рак'), ('leo', 'Лев'), ('virgo', 'Дева'), ('libra', 'Весы'), ('scorpio', 'Скорпион'), ('sagittarius', 'Стрелец'), ('capricorn', 'Козерог'), ('aquarius', 'Водолей'), ('pisces', 'Рыбы')], max_length=20, verbose_name='Знак зодиака')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Гороскоп',
                'verbose_name_plural': 'Гороскопы',
                'ordering': ['-date', 'sign'],
                'constraints': [models.UniqueConstraint(fields=('date', 'sign'), name='unique_sign_date')],
            },
        ),
    ]
